### ISSUE TITLE
JPA 기본키 사용 전략 질문

### ISSUE THREAD

**Issue by jikimee64** [bsideproject/palette-api-server#22]
@Player1789 
아래와 같이 기본키 전략을 **GenerationType.AUTO**로 만드신 이유가 있을까요?

```
@MappedSuperclass
@EqualsAndHashCode(of = "id")
@Getter
public abstract class BaseEntity {
    @Id
    @GeneratedValue(strategy = **GenerationType.AUTO**)
```

해당 시퀀스 전략으로 할 시 
MySQL이라면 sequences를 지원하지 않기 때문에 TABLE Generator
시퀀스 테이블이 따로 생성되네요 
![image](https://user-images.githubusercontent.com/52563841/183110670-ee3b0e5f-9bc5-41b9-ba66-7936fd1dc79e.png)

저는 아래블로그를 참고해서 AUTO_INCREMENT 전략이 간단하고 성능면에서 좋다고 생각했습니다!

참고 블로그
[Mysql 'GenerationType.AUTO' 동작 방식 ](https://rutgo-letsgo.tistory.com/306)
[권장하는 식별자 전략 참고](https://velog.io/@conatuseus/%EC%97%94%ED%8B%B0%ED%8B%B0-%EB%A7%A4%ED%95%91-2-msk0kq84v5)

**Comment by Player1789** [comment]
@jikimee64 질문 주셔서 감사합니다!
GenerationType.AUTO로 지정한 이유는 따로 없습니다.
아마 우철님께서 주셨던 레퍼런스에 있었는데 제가 어떤 기능인지 확인을 안하고 추가했나봅니다.
AUTO_INCREMENT 방식 좋은 것 같습니다.
다음 커밋때 반영하겠습니다.

**Comment by Player1789** [comment]
#26 에 해당사항 반영했습니다!
알려주셔서 감사합니다!
