### ISSUE TITLE
Fix: 토큰페이로드에 id(PK), email 추가 필요

### ISSUE THREAD

**Issue by jikimee64** [bsideproject/palette-api-server#45]
- 토큰 페이로드에 id(PK), email 추가 필요
  - 이메일: 일기 작성기간동안 상대방의 일기를 볼수 없게 만들기 위한 구분값

erd 참고
https://www.erdcloud.com/d/MsruraFqdY4onEkAW

화면 기획 참고
https://www.figma.com/file/imyeORdFTy1qVaP0wmVn13/%EB%B0%98%EC%AA%BD%EC%9D%BC%EA%B8%B0-%EA%B8%B0%ED%9A%8D?node-id=128%3A7513

**Comment by Player1789** [comment]
#73
