### ISSUE TITLE
Fix: 업로드 시 파일경로 규칙 설정

### ISSUE THREAD

**Issue by jikimee64** [bsideproject/palette-api-server#46]
- 내생각
  - /년/월/일/{UUID 랜덤값}.{확장자}
  - UUID 랜덤값 생성시 '-' 제거
    - 자바 코드 참고 https://kitchu.tistory.com/59
  - ex) /2022/08/16/550e8400e29b41d4a716446655440000.jpg

**Comment by Player1789** [comment]
일단 보류
